name: Handle stale issues
on:
  schedule:
  - cron: "30 7 * * *"
  
  workflow_dispatch:
  
jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been marked stale because it has been open 60 days with no activity.'
        stale-issue-label: 'stale'
        days-before-stale: 60
        days-before-close: -1
